#  Python Tuples â€” DSA Theory

A **Tuple** in Python is an **ordered, immutable sequence of elements**.

---

## Characteristics:

- **Indexed:** Elements are accessed via zero-based index.
- **Immutable:** Once created, elements cannot be added, removed, or changed.
- **Allows Duplicates:** Tuples can have multiple occurrences of the same value.
- **Heterogeneous:** Can store elements of different data types.
- **Faster than lists** for fixed-sized collections because of immutability.

---

## Internal Implementation:

Tuples are implemented as **static arrays**, where the size is fixed after creation.  
This makes them faster and more memory-efficient for **read-only data**.

---

## Common Operations in Tuples:

| Operation      | Description                                              |
|:---------------|:---------------------------------------------------------|
| `index()`       | Returns the index of the first occurrence of a value     |
| `count()`       | Counts the number of times a value appears               |
| `len()`         | Returns the number of elements in the tuple              |
| `max()` / `min()`| Returns the largest / smallest element                  |
| `sum()`         | Returns the sum of numeric elements (if applicable)      |
| `tuple()`       | Converts an iterable (like a list) into a tuple          |

---

###  Declaration of Tuples

In [ ]:
# Creating a tuple
my_tuple = (10, 20, 30, 40, 50)

# Display the tuple
print("Tuple:", my_tuple)

# Functions

### 1. index()

In [ ]:
# Given tuple
my_tuple = (10, 20, 30, 20, 40)

# Find index of first occurrence of 20
index_of_20 = my_tuple.index(20)

# Print the index
print("Index of 20:", index_of_20)

### 2. count ()

In [ ]:
# Given tuple
my_tuple = (10, 20, 10, 30, 10, 40)

# Count how many times 10 appears
count_10 = my_tuple.count(10)

# Print the count
print("Count of 10:", count_10)

## 3. len ()

In [ ]:
# Given tuple
my_tuple = (10, 20, 30, 40)

# Find the length
length = len(my_tuple)

# Print the length
print("Length of tuple:", length)

## 4. min () and max ()

In [ ]:
# Given tuple
my_tuple = (10, 20, 30, 40)

# Find max and min values
maximum_value = max(my_tuple)
minimum_value = min(my_tuple)

# Print values
print("Max value:", maximum_value)
print("Min value:", minimum_value)

## 5. sum ()

In [ ]:
# Given tuple
my_tuple = (10, 20, 30, 40)

# Calculate sum
total = sum(my_tuple)

# Print the sum
print("Sum of tuple:", total)

# 6. tuple ()

In [ ]:
# Given list
my_list = [10, 20, 30, 40]

# Convert to tuple
my_tuple = tuple(my_list)

# Print the tuple
print("Converted tuple:", my_tuple)

# DSA Problems on Tuples

### 1. Given a tuple of numbers and a target element, find and print all indexes where the target element occurs in the tuple.

In [1]:
my_tuple = (10, 20, 30, 20, 40, 20)
target = 20

indexes = []
for i in range(len(my_tuple)):
    if my_tuple[i] == target:
        indexes.append(i)

print(indexes)

[1, 3, 5]

## 2: Flatten a Tuple of Tuples

In [ ]:
nested_tuple = ((1, 2), (3, 4), (5, 6))
flat_list = []

for t in nested_tuple:
    for num in t:
        flat_list.append(num)

flat_tuple = tuple(flat_list)
print(flat_tuple)

## 3. Swap First and Last Elements

In [2]:
my_tuple = (10, 20, 30, 40)
temp = list(my_tuple)

temp[0], temp[-1] = temp[-1], temp[0]

new_tuple = tuple(temp)
print(new_tuple)

(40, 20, 30, 10)

 ## 4: Find Second Largest Element

In [ ]:
my_tuple = (10, 40, 30, 20, 50)
my_list = list(my_tuple)

my_list.sort()
second_largest = my_list[-2]

print(second_largest)

## 5: Check if Two Tuples are Identical

In [ ]:
tuple1 = (10, 20, 30)
tuple2 = (10, 20, 30)

print(tuple1 == tuple2)